# Generated by Django 3.1.7 on 2021-03-24 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('rut', models.IntegerField(blank=True)),
                ('horario', models.TimeField(default='12:00')),
                ('telefono', models.IntegerField()),
                ('sitio_web', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electónico')),
            ],
            options={
                'verbose_name_plural': 'Distribuidores',
            },
        ),
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('wh', 'Whisky'), ('ce', 'Cerveza'), ('vi', 'Vino'), ('li', 'Licor')], default='vi', max_length=2)),
                ('marca', models.CharField(default='', max_length=30, verbose_name='Marca')),
                ('contenido_neto', models.CharField(max_length=6, verbose_name='Cont.Neto')),
                ('stock', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('origen', models.CharField(max_length=30)),
                ('imagen', models.ImageField(upload_to='bebida_img')),
                ('distribuidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bebidas.distribuidor')),
            ],
        ),
    ]
