# Generated by Django 3.1.7 on 2021-03-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebidas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribuidor',
            name='horariocierre',
            field=models.TimeField(default='18:00', verbose_name='Horario de Cierre'),
        ),
        migrations.AlterField(
            model_name='distribuidor',
            name='horario',
            field=models.TimeField(default='08:00', verbose_name='Horario de Apertura'),
        ),
        migrations.AlterField(
            model_name='distribuidor',
            name='telefono',
            field=models.CharField(max_length=12),
        ),
    ]
