# Generated by Django 3.1.7 on 2021-03-31 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebidas', '0002_auto_20210324_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bebida',
            options={'verbose_name_plural': 'Bebidas'},
        ),
        migrations.AlterField(
            model_name='bebida',
            name='categoria',
            field=models.CharField(choices=[('Whisky', 'Whisky'), ('Cervezas', 'Cerveza'), ('Vinos', 'Vino'), ('Licores', 'Licor')], default='Vinos', max_length=8),
        ),
    ]
