# Generated by Django 3.1.7 on 2021-03-31 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebidas', '0003_auto_20210330_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebida',
            name='categoria',
            field=models.CharField(choices=[('Whisky', 'Whisky'), ('Cerveza', 'Cerveza'), ('Vino', 'Vino'), ('Licores', 'Licor')], default='Vino', max_length=8),
        ),
    ]
